/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.ThuPhiManagerFrame;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author conghoang
 */
public class ThemThongTinThuPhiJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ThemDotThuPhi
     */
    private JFrame parentFrame;
    public ThemThongTinThuPhiJFrame(JFrame parentFrame) {
        this.parentFrame = parentFrame;
        this.parentFrame.setEnabled(false);
        initComponents();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Are you sure to close??", "Warning!!", JOptionPane.YES_NO_OPTION) == 0) {
                    close();
                }
            }
            
        });
    }
    void close() {
        this.parentFrame.setEnabled(true);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MaDotThuPhi = new javax.swing.JLabel();
        IDHoKhau = new javax.swing.JLabel();
        NgayThuPhi = new javax.swing.JLabel();
        SoTien = new javax.swing.JLabel();
        MaDotThuPhiText = new javax.swing.JTextField();
        SoTienText = new javax.swing.JTextField();
        TenDotThuPhiText = new javax.swing.JTextField();
        NgayBatDauText = new javax.swing.JTextField();
        CancelButton = new javax.swing.JButton();
        CreateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MaDotThuPhi.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        MaDotThuPhi.setText("Mã đợt thu phí");

        IDHoKhau.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        IDHoKhau.setText("ID Hộ Khẩu");

        NgayThuPhi.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        NgayThuPhi.setText("Ngày Thu Phí");

        SoTien.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        SoTien.setText("Số Tiền");

        SoTienText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoTienTextActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");

        CreateButton.setText("Create");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MaDotThuPhi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(IDHoKhau)
                            .addComponent(NgayThuPhi)
                            .addComponent(SoTien))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MaDotThuPhiText, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(SoTienText)
                            .addComponent(TenDotThuPhiText)
                            .addComponent(NgayBatDauText)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(CancelButton)
                        .addGap(63, 63, 63)
                        .addComponent(CreateButton)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MaDotThuPhi)
                        .addComponent(MaDotThuPhiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IDHoKhau)
                    .addComponent(SoTienText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NgayThuPhi)
                    .addComponent(TenDotThuPhiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SoTien)
                    .addComponent(NgayBatDauText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(CreateButton))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SoTienTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoTienTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SoTienTextActionPerformed

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CreateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton CreateButton;
    private javax.swing.JLabel IDHoKhau;
    private javax.swing.JLabel MaDotThuPhi;
    private javax.swing.JTextField MaDotThuPhiText;
    private javax.swing.JTextField NgayBatDauText;
    private javax.swing.JLabel NgayThuPhi;
    private javax.swing.JLabel SoTien;
    private javax.swing.JTextField SoTienText;
    private javax.swing.JTextField TenDotThuPhiText;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
